# NUMPY

1.np.array(object, ...) - создание массива из объекта + разные условия.  
2.

In [1]:
import numpy as np

## Простые действия

In [2]:
%%time
#Большое время выполнения
arr = []
n = 10**7
for i in range(n):
    arr.append(i * 5)

CPU times: user 3.05 s, sys: 238 ms, total: 3.29 s
Wall time: 3.28 s


In [3]:
%%time
#Большое время выполнения

def summ(a):
    rez = 0
    for i in arr:
        rez += i
    return rez

arr = range(10**7)

print(summ(arr))

49999995000000
CPU times: user 1.09 s, sys: 75.8 ms, total: 1.17 s
Wall time: 1.17 s


In [4]:
!which python3.9

/usr/bin/python3.9


In [5]:
a = [1, 2, 3]
a

[1, 2, 3]

In [19]:
b = np.array(a, dtype='float64')

In [7]:
print(a, type(a), b, type(b))

[1, 2, 3] <class 'list'> [1. 2. 3.] <class 'numpy.ndarray'>


**Если в списке (а) будут разные типы, то приведет к одному по приоритетности (н-р: стр выше инт, т.к. инт всегда можно преобразовать в стр)**

In [3]:
d = np.array([4, 5, 6])
print(d)

[4 5 6]


In [4]:
a @ d

32

In [6]:
np.transpose(a)

array([1, 2, 3])

In [16]:
a, d

([1, 2, 3], array([4, 5, 6]))

In [12]:
d

array([4, 5, 6])

In [10]:
a

[1, 2, 3]

In [13]:
d + 1


array([5, 6, 7])

In [14]:
d

array([4, 5, 6])

In [15]:
d[0]

4

In [11]:
np.transpose(a).dot(d)

32

In [9]:
a.dot(d)

AttributeError: 'list' object has no attribute 'dot'

In [9]:
print(type(a), type(b), type(d))

<class 'list'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


**посмотрим методы класса ndarray**

In [10]:
set(dir(d)) - set(dir(object)) #Уберем из методов все методы для объектов

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',

In [11]:
? d.nbytes

In [12]:
d.nbytes # 4 эл-та по 8 байтов! Т.к. тип инт64

24

In [13]:
c = np.array([5, 6, 2, 1, 10], dtype='int32')

In [14]:
c.nbytes #32 бита, т.е. 32/8 = 4 байта. 5элементов по 4 байта!

20

In [15]:
array = np.array([[[1, 2, 3, 4],
                 [2, 3, 4, 5],
                 [2, 2, 4, 3]],
                [[1, 1, 2, 1],
                [3, 4, 3, 3],
                [4, 3, 2, 1]]])

In [16]:
array

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [2, 2, 4, 3]],

       [[1, 1, 2, 1],
        [3, 4, 3, 3],
        [4, 3, 2, 1]]])

In [17]:
type(array)

numpy.ndarray

In [18]:
len(array)

2

In [19]:
array.size

24

In [20]:
array.ndim

3

In [21]:
array.shape

(2, 3, 4)

In [22]:
array[-1]

array([[1, 1, 2, 1],
       [3, 4, 3, 3],
       [4, 3, 2, 1]])

In [23]:
p = [2, 3, 5, 7]
p_arr = np.array(p)
print(p_arr.dtype, type(p_arr), p_arr.shape, p_arr.nbytes)

int64 <class 'numpy.ndarray'> (4,) 32


In [24]:
a = np.zeros(9)

In [25]:
b = np.ones(5, dtype='int64')

In [26]:
print(a, b)

[0. 0. 0. 0. 0. 0. 0. 0. 0.] [1 1 1 1 1]


In [27]:
eq = np.zeros_like(b) #Лайк удобно, копирует не только значения, но и тип
print(eq)

[0 0 0 0 0]



**np.arange похож на range, Start/Stop/Step. Аргументы могут быть float!!! Аккуратнее, округления!**   
**- np.arange(Start, Stop) Step = 1!**  
**- np.arange(Stop) Start = 0, Step = 1!**

In [28]:
print(np.arange(1, 25, 4))
print(np.arange(3., 14, 2))
print(np.arange(7, 15))
print(np.arange(6))

[ 1  5  9 13 17 21]
[ 3.  5.  7.  9. 11. 13.]
[ 7  8  9 10 11 12 13 14]
[0 1 2 3 4 5]


**np.linspace(Start, End, Count) в диапазоне от старт до конец сделать какое-то кол-во одинаковых промежутков**

In [29]:
np.linspace(3, 10, 12)

array([ 3.        ,  3.63636364,  4.27272727,  4.90909091,  5.54545455,
        6.18181818,  6.81818182,  7.45454545,  8.09090909,  8.72727273,
        9.36363636, 10.        ])

In [30]:
k = np.linspace(10, 32, 12)
print(k, k[1] - k[0], sep='\n')

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


**np.logspace(Start= степень 10, End= степень 10, Count) тоже, что и линспэйс, но начало и конец - 10 в степени...**

In [31]:
print(np.logspace(0, 3, 12))

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


## Операции над массивами

**Все действия с массивами "+, -, *. /" поэлементно!!!**

In [32]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)

In [33]:
print('\n\n') #Прикольная штука, делает большие отступы в тетрадке!
print(f'a = {a}, b = {b}', '\n\n', a+b, a-b, a*b, a/b, sep='\n')




a = [ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.], b = [ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


In [34]:
print((a + b)**2, 2**(a + b)[:3], sep='\n') #можно любые арифм операции, слайсы и т.д, также поэлементно!

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2. 4. 8.]


**Есть элементарные ф-ии, применяемые также поэлементно!!!**

In [35]:
print(np.cos(a))

[-0.9899925   0.96017029 -0.91113026  0.84385396 -0.75968791  0.66031671
 -0.54772926  0.42417901 -0.29213881  0.15425145 -0.01327675]


**Если нельзя провести операцию над ячейкой, то не будет краш, запишется nan**

In [36]:
print(b, np.log(b)) #В массиве в - отрицательные числа, log отриц чисел нет

[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.] [nan nan nan nan nan nan nan nan nan nan nan]


/tmp/ipykernel_56833/3279071292.py:1: RuntimeWarning: invalid value encountered in log
  print(b, np.log(b)) #В массиве в - отрицательные числа, log отриц чисел нет


In [37]:
print(a>b, a==b, a>=10, sep='\n') #Сравнение также поэлементно

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


**Кванторы существования и всеобщности**

**np.any(Существования)** Существует хотябы один элемент массива, удовлетворяющий условию...

In [38]:
d = np.array([0, 4, 5, 6])

In [39]:
np.any(d == 0)

True

**np.all(Всеобщности)** Для всех эл-тов массива верно условие...

In [40]:
np.all(d == 0)

False

**Деление на ноль даcт nan, если 0/0, или +-inf(бесконечность). Ошибки не бросает!!!**

In [41]:
f = np.array([3, 2, 1, 9])

In [42]:
print(f / d)

[inf 0.5 0.2 1.5]


/tmp/ipykernel_56833/2365881351.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(f / d)


**Константы**

In [43]:
print(np.e, np.pi, sep='\n')

2.718281828459045
3.141592653589793


**Куммулятивная ф-я. В каждой следующей ячейке сумма предыдущих**

In [44]:
b

array([ -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18., -20., -22.])

In [45]:
b.cumsum()

array([  -2.,   -6.,  -12.,  -20.,  -30.,  -42.,  -56.,  -72.,  -90.,
       -110., -132.])

**Сортировка**

Как ф-я np.sort(var) - не меняет исходный массив, как метод var.sort() - меняет исходный массив. 

In [46]:
f = np.array([3, 2, 1, 9])

In [47]:
print(np.sort(f), f, sep='\n')

[1 2 3 9]
[3 2 1 9]


In [48]:
f.sort()
print(f)

[1 2 3 9]


**Массивы можно соединять и расщеплять**

In [49]:
print(a, b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.] [ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]


In [50]:
#Соединяем
np.hstack((a, b, a + b)) #На вход подаем 1 элемент, кортеж из того, что хотим объединить
#Будут записаны последовательно, как аргументы метода

array([  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,  33.,
        -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18., -20., -22.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.])

In [51]:
#Разъединяем, массивов будет n + 1 (n- число отсечек, слайсов, от 0 до 1 не вкл, от 1 до 2 не вкл и т.д. )
print(a)
m1, m2, m3, m4 = np.hsplit(a, [2, 7, 10]) #если указать последний, то будет еще нулевой массив, т.е все равно n + 1
print(m1, m2, m3, m4, sep='\n')

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[3. 6.]
[ 9. 12. 15. 18. 21.]
[24. 27. 30.]
[33.]


**Функции append, delete, insert НЕ ИЗМЕНЯЮТ исходный массив!!!***

In [52]:
a

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33.])

In [53]:
print(np.delete(a, [1, 3, 7, 8]))
print(a)
print(np.append(a, [36, 39,42,45]))
print(a)

[ 3.  9. 15. 18. 21. 30. 33.]
[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45.]
[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]


In [54]:
#insert похож на append, только 3 аргумента, второй аргумент - индекс массива до которого вставим что хотим
print(np.insert(a, 2, [7, 8]))

[ 3.  6.  7.  8.  9. 12. 15. 18. 21. 24. 27. 30. 33.]


## Индексирование

**Не забыть, что если назвать слайс другой переменной, то она ссылается на ту же область памяти, что и основной массив! Т.е. при изменениях будем видеть их во всех переменных.**

In [55]:
b = 

SyntaxError: invalid syntax (948568665.py, line 1)

In [ ]:
b[::-1] #Стандартно - обратный порядок

**copy Чтобы избежать изменений в исходном массиве**

In [ ]:
a

In [ ]:
b

In [ ]:
b = a.copy() #Теперь ссылаются на разные области, можно менять как хотим

In [ ]:
b

In [ ]:
mass = np.linspace(-4*np.pi, 4*np.pi, 100)

In [ ]:
mass1 = (np.cos(mass) ** 2 + np.sin(mass) ** 2).round() #Обязательно!!!!!!!!!! Это не круглые единицы!!!

In [ ]:
mass1

In [ ]:
np.all(mass1 == 1) #Без роунда (округления) получим False!!!

## Двумерные массивы

In [60]:
a = np.array([[1, 2], [3, 4]]) #На вход список списков

In [61]:
a #Выводится всегда красиво в виде матрицы

array([[1, 2],
       [3, 4]])

In [62]:
a.ndim, a.size, a.shape, len(a)

(2, 4, (2, 2), 2)

In [63]:
print(a[1], a[1][0], a[1, 1], a[0][1], a[0, 0], sep='\n') #Слайсы без проблем, можно с запятой

[3 4]
3
4
2
1


In [64]:
w = np.array([[5, 6], [7]]) #Запишет массив из двух списков!!!
print(w)

[list([5, 6]) list([7])]


/tmp/ipykernel_56833/2404157978.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  w = np.array([[5, 6], [7]]) #Запишет массив из двух списков!!!


**Можно быстро разбить массив на несколько массивов без изменения данных**

In [56]:
b = np.arange(0, 20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
b.shape = (2, 10) #Всегда size должен быть одинаковый!!! Здесь - 20
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [58]:
b.shape = (4, 5) #И здесь 20
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
b.shape = (20) #Одинаково с (1, 20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Быстро растянуть можно и так:

In [65]:
b.shape = (4, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
b.ravel() #Но сам массив не изменится!!!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**Любые массивы нулей и единиц, если указываем кортеж, который фактически shape**

In [67]:
s = np.ones((3, 6))
s

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [98]:
n = np.zeros((3, 3), dtype='int64')
n

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [69]:
g = np.zeros((2, 3, 8))

In [70]:
g

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

**А вот и единичная матрица!**

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Также можно построить матрицу со значениями по диагонали, остальные нули

In [72]:
np.diag(np.array([1, 2, 5, 7]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

**Мое решение задачки**

In [89]:
x = np.zeros(8, dtype='int64')
print(x)
x[:] = 3
print(x)
np.diag(x.cumsum())

[0 0 0 0 0 0 0 0]
[3 3 3 3 3 3 3 3]


array([[ 3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 18,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 21,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 24]])

In [74]:
y = np.zeros(8, dtype='int64')
y[:] = -1
z = np.diag(y)
z

array([[-1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1]])

In [75]:
rez_m = z[::-1] + np.diag(x.cumsum())
rez_m

array([[ 3,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  6,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  9,  0,  0, -1,  0,  0],
       [ 0,  0,  0, 12, -1,  0,  0,  0],
       [ 0,  0,  0, -1, 15,  0,  0,  0],
       [ 0,  0, -1,  0,  0, 18,  0,  0],
       [ 0, -1,  0,  0,  0,  0, 21,  0],
       [-1,  0,  0,  0,  0,  0,  0, 24]])

In [76]:
#Решение в одну строку!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
rez_m2 = -1*np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))
rez_m2

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  6.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  9.,  0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0., 12., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1., 15.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0., 18.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0., 21.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0., 24.]])

**Умножение матриц**

In [77]:
a = 5 * np.ones((5, 5))
b = 1 + np.eye(5)
print(a, '\n\n', b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

 [[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [78]:
print(a * b) #Умножение поэлементное

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]]


In [79]:
print(a @ b) #Матричное умножение. НЕСИММЕТРИЧНО и т.д.!!!

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


In [80]:
print(a.dot(b)) #Матричное умножение! (==a@b)

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


Непонятная фигня с мешгрид

In [ ]:
u = np.linspace(1, 2, 2)
v = np.linspace(4, 8, 3)
print(u, v, sep='\n')

In [ ]:
np.meshgrid(u, v)

## Тензоры (многомерные массивы)

In [82]:
X = np.arange(64).reshape(8, 2, 4) #Вроде shape тоже самое, но не работает???
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [83]:
print(f'shape = {X.shape}, ndim = {X.ndim}, len = {len(X)}, size = {X.size}')

shape = (8, 2, 4), ndim = 3, len = 8, size = 64


**Суммы**

In [84]:
np.sum(X) #Это просто сумма всех элементов матрицы

2016

In [85]:
(63 * 64)/2 #Проверка предыдущей суммы по известной формуле. Это просто сумма всех элементов матрицы

2016.0

**По осям**

In [86]:
np.sum(X, axis=0) #Просто поэлементное сложение матриц

array([[224, 232, 240, 248],
       [256, 264, 272, 280]])

In [87]:
np.sum(X, axis=1) #Все суммы полей в 1-й матрице, потом во второй, потом в третей...

array([[  4,   6,   8,  10],
       [ 20,  22,  24,  26],
       [ 36,  38,  40,  42],
       [ 52,  54,  56,  58],
       [ 68,  70,  72,  74],
       [ 84,  86,  88,  90],
       [100, 102, 104, 106],
       [116, 118, 120, 122]])

In [88]:
np.sum(X, axis=2) #Суммы строк в 1-й матрице, потом во второй, потом в третей...

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118],
       [134, 150],
       [166, 182],
       [198, 214],
       [230, 246]])

In [ ]:
np.sum(X, axis=(1, 2)) #Сначала axis=1, потом к ней уже axis=2 (сумма строк)

## ЛинАл

In [ ]:
a = np.array([[2, 1], [2, 3]])
a

Определитель

In [ ]:
np.linalg.det(a)

Нахождение обратной

In [ ]:
b = np.linalg.inv(a)
b

In [ ]:
#Проверим
print(a @ b)
print(b.dot(a))

In [ ]:
c = np.array([[2, 1], [6, 3]])

In [ ]:
np.linalg.det(c) #В этом питоне все нормально, это ____ матрица!!!

In [ ]:
np.linalg.inv(c) #Как следствие - обратной матрицы не существует!

Решение Неоднородных Линейных Уравнений  
**Здесь запутка какая-то, результат не получился**

In [ ]:
v = np.array([5, -10])
v

In [ ]:
c = np.linalg.solve(a, v)

In [ ]:
b

In [ ]:
b.dot(a)

In [ ]:
a

In [ ]:
b

In [ ]:
a @ b

In [ ]:
b @ 

Собственный вектор

In [ ]:
a

In [ ]:
l, u = np.linalg.eig(a) #Первый аргумент - собственный числа, вторым - собственные вектора
print(l, '\n', u)

In [ ]:
l_T, u_T = np.linalg.eig(a.T) #Собств числа у транспонированной матрицы теже, а ветора несколько отличаются
print(l_T, '\n', u_T)

## Производительность

In [ ]:
%%time

summ_arr = np.sum(np.arange(10**7))
print(summ_arr)

In [ ]:
%%time

arr = 5 * np.arange(10**7)

In [91]:
import numpy as np
import random
import scipy.stats as sps